image:
  repository: harbor-dev.onedev.neustar.biz/onedev-common/velero
  tag: latest

## Default s3 bucket for storing all backup files created by the backup-restore-operator
backupsEnabled: true
configuration:
  provider: AWS
  backupStorageLocation:
    provider: AWS
    bucketName: dc15-cmf-prd
    prefix: dc15-cmf-prd-bkups
    region: ap-south
    endpoint: http://dc15-flashblade01.neustar.net
    endpointCA: ""
    insecureTLSSkipVerify: false

s3:
  enabled: true
  ## credentialSecretName if set, should be the name of the Secret containing AWS credentials.
  ## To use IAM Role, don't set this field
  credentialSecretName: "velero-credentials"
  credentialSecretNamespace: "velero"
  provider: AWS
  region: "ap-south"
  bucketName: "dc15-cmf-prd"
  prefix: "dc15-cmf-prd-bkups "
  endpoint: "http://dc15-flashblade01.neustar.net "
  endpointCA: ""
  insecureTLSSkipVerify: false

kubectl:
  image:
    repository: harbor-dev.onedev.neustar.biz/onedev-common/kubectl

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  annotations: {}

priorityClassName: ""
